// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: github.com/danhol86/dhmessagesapi/messages/protos.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SENDMESSAGE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1     string `protobuf:"bytes,1,opt,name=id1,proto3" json:"id1,omitempty"`
	P2      int32  `protobuf:"varint,2,opt,name=p2,proto3" json:"p2,omitempty"`
	Message []byte `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Id2     string `protobuf:"bytes,6,opt,name=id2,proto3" json:"id2,omitempty"`
}

func (x *SENDMESSAGE) Reset() {
	*x = SENDMESSAGE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SENDMESSAGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SENDMESSAGE) ProtoMessage() {}

func (x *SENDMESSAGE) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SENDMESSAGE.ProtoReflect.Descriptor instead.
func (*SENDMESSAGE) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{0}
}

func (x *SENDMESSAGE) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *SENDMESSAGE) GetP2() int32 {
	if x != nil {
		return x.P2
	}
	return 0
}

func (x *SENDMESSAGE) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SENDMESSAGE) GetId2() string {
	if x != nil {
		return x.Id2
	}
	return ""
}

type PRCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1 *PRCreate_PRCP1Scheme `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2 *PRCreate_PRCP2Scheme `protobuf:"bytes,3,opt,name=p2,proto3" json:"p2,omitempty"`
	P3 *PRCreate_PRCP3Scheme `protobuf:"bytes,4,opt,name=p3,proto3" json:"p3,omitempty"`
}

func (x *PRCreate) Reset() {
	*x = PRCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate) ProtoMessage() {}

func (x *PRCreate) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate.ProtoReflect.Descriptor instead.
func (*PRCreate) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1}
}

func (x *PRCreate) GetP1() *PRCreate_PRCP1Scheme {
	if x != nil {
		return x.P1
	}
	return nil
}

func (x *PRCreate) GetP2() *PRCreate_PRCP2Scheme {
	if x != nil {
		return x.P2
	}
	return nil
}

func (x *PRCreate) GetP3() *PRCreate_PRCP3Scheme {
	if x != nil {
		return x.P3
	}
	return nil
}

type PRRecieve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1     *PRRecieve_PRRP1Scheme `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2     *PRRecieve_PRRP2Scheme `protobuf:"bytes,2,opt,name=p2,proto3" json:"p2,omitempty"`
	Keyenc []byte                 `protobuf:"bytes,3,opt,name=keyenc,proto3" json:"keyenc,omitempty"`
	Phone1 int32                  `protobuf:"varint,4,opt,name=phone1,proto3" json:"phone1,omitempty"`
	P5     *PRRecieve_PRRP5Scheme `protobuf:"bytes,5,opt,name=p5,proto3" json:"p5,omitempty"`
	Guid   string                 `protobuf:"bytes,6,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *PRRecieve) Reset() {
	*x = PRRecieve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRRecieve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRRecieve) ProtoMessage() {}

func (x *PRRecieve) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRRecieve.ProtoReflect.Descriptor instead.
func (*PRRecieve) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{2}
}

func (x *PRRecieve) GetP1() *PRRecieve_PRRP1Scheme {
	if x != nil {
		return x.P1
	}
	return nil
}

func (x *PRRecieve) GetP2() *PRRecieve_PRRP2Scheme {
	if x != nil {
		return x.P2
	}
	return nil
}

func (x *PRRecieve) GetKeyenc() []byte {
	if x != nil {
		return x.Keyenc
	}
	return nil
}

func (x *PRRecieve) GetPhone1() int32 {
	if x != nil {
		return x.Phone1
	}
	return 0
}

func (x *PRRecieve) GetP5() *PRRecieve_PRRP5Scheme {
	if x != nil {
		return x.P5
	}
	return nil
}

func (x *PRRecieve) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type QR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1 []byte `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2 []byte `protobuf:"bytes,2,opt,name=p2,proto3" json:"p2,omitempty"`
	P3 []byte `protobuf:"bytes,3,opt,name=p3,proto3" json:"p3,omitempty"`
}

func (x *QR) Reset() {
	*x = QR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QR) ProtoMessage() {}

func (x *QR) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QR.ProtoReflect.Descriptor instead.
func (*QR) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{3}
}

func (x *QR) GetP1() []byte {
	if x != nil {
		return x.P1
	}
	return nil
}

func (x *QR) GetP2() []byte {
	if x != nil {
		return x.P2
	}
	return nil
}

func (x *QR) GetP3() []byte {
	if x != nil {
		return x.P3
	}
	return nil
}

type UserScan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UserScan_UserScanData `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UserScan) Reset() {
	*x = UserScan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScan) ProtoMessage() {}

func (x *UserScan) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScan.ProtoReflect.Descriptor instead.
func (*UserScan) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{4}
}

func (x *UserScan) GetData() *UserScan_UserScanData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PRCreate_PRCP1Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid  string                            `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Bugle string                            `protobuf:"bytes,3,opt,name=bugle,proto3" json:"bugle,omitempty"`
	P1    *PRCreate_PRCP1Scheme_PRCDateTime `protobuf:"bytes,7,opt,name=p1,proto3" json:"p1,omitempty"`
}

func (x *PRCreate_PRCP1Scheme) Reset() {
	*x = PRCreate_PRCP1Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate_PRCP1Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate_PRCP1Scheme) ProtoMessage() {}

func (x *PRCreate_PRCP1Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate_PRCP1Scheme.ProtoReflect.Descriptor instead.
func (*PRCreate_PRCP1Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PRCreate_PRCP1Scheme) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *PRCreate_PRCP1Scheme) GetBugle() string {
	if x != nil {
		return x.Bugle
	}
	return ""
}

func (x *PRCreate_PRCP1Scheme) GetP1() *PRCreate_PRCP1Scheme_PRCDateTime {
	if x != nil {
		return x.P1
	}
	return nil
}

type PRCreate_PRCP2Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Browser string `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Bnum    int32  `protobuf:"varint,2,opt,name=bnum,proto3" json:"bnum,omitempty"`
	Os      string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PRCreate_PRCP2Scheme) Reset() {
	*x = PRCreate_PRCP2Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate_PRCP2Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate_PRCP2Scheme) ProtoMessage() {}

func (x *PRCreate_PRCP2Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate_PRCP2Scheme.ProtoReflect.Descriptor instead.
func (*PRCreate_PRCP2Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PRCreate_PRCP2Scheme) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *PRCreate_PRCP2Scheme) GetBnum() int32 {
	if x != nil {
		return x.Bnum
	}
	return 0
}

func (x *PRCreate_PRCP2Scheme) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PRCreate_PRCP2Scheme) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PRCreate_PRCP3Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1 *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme `protobuf:"bytes,6,opt,name=p1,proto3" json:"p1,omitempty"`
}

func (x *PRCreate_PRCP3Scheme) Reset() {
	*x = PRCreate_PRCP3Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate_PRCP3Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate_PRCP3Scheme) ProtoMessage() {}

func (x *PRCreate_PRCP3Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate_PRCP3Scheme.ProtoReflect.Descriptor instead.
func (*PRCreate_PRCP3Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1, 2}
}

func (x *PRCreate_PRCP3Scheme) GetP1() *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme {
	if x != nil {
		return x.P1
	}
	return nil
}

type PRCreate_PRCP1Scheme_PRCDateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year   int32 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month  int32 `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Day    int32 `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	Hour   int32 `protobuf:"varint,7,opt,name=hour,proto3" json:"hour,omitempty"`
	Second int32 `protobuf:"varint,9,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) Reset() {
	*x = PRCreate_PRCP1Scheme_PRCDateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate_PRCP1Scheme_PRCDateTime) ProtoMessage() {}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate_PRCP1Scheme_PRCDateTime.ProtoReflect.Descriptor instead.
func (*PRCreate_PRCP1Scheme_PRCDateTime) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *PRCreate_PRCP1Scheme_PRCDateTime) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bnum   int32  `protobuf:"varint,1,opt,name=bnum,proto3" json:"bnum,omitempty"`
	Keyenc []byte `protobuf:"bytes,2,opt,name=keyenc,proto3" json:"keyenc,omitempty"`
}

func (x *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) Reset() {
	*x = PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) ProtoMessage() {}

func (x *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme.ProtoReflect.Descriptor instead.
func (*PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) GetBnum() int32 {
	if x != nil {
		return x.Bnum
	}
	return 0
}

func (x *PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme) GetKeyenc() []byte {
	if x != nil {
		return x.Keyenc
	}
	return nil
}

type PRRecieve_PRRP1Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int32 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PRRecieve_PRRP1Scheme) Reset() {
	*x = PRRecieve_PRRP1Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRRecieve_PRRP1Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRRecieve_PRRP1Scheme) ProtoMessage() {}

func (x *PRRecieve_PRRP1Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRRecieve_PRRP1Scheme.ProtoReflect.Descriptor instead.
func (*PRRecieve_PRRP1Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PRRecieve_PRRP1Scheme) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PRRecieve_PRRP2Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P2Id    int32  `protobuf:"varint,1,opt,name=p2id,proto3" json:"p2id,omitempty"`
	P2Str   string `protobuf:"bytes,2,opt,name=p2str,proto3" json:"p2str,omitempty"`
	P2Bugle string `protobuf:"bytes,3,opt,name=p2bugle,proto3" json:"p2bugle,omitempty"`
}

func (x *PRRecieve_PRRP2Scheme) Reset() {
	*x = PRRecieve_PRRP2Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRRecieve_PRRP2Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRRecieve_PRRP2Scheme) ProtoMessage() {}

func (x *PRRecieve_PRRP2Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRRecieve_PRRP2Scheme.ProtoReflect.Descriptor instead.
func (*PRRecieve_PRRP2Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{2, 1}
}

func (x *PRRecieve_PRRP2Scheme) GetP2Id() int32 {
	if x != nil {
		return x.P2Id
	}
	return 0
}

func (x *PRRecieve_PRRP2Scheme) GetP2Str() string {
	if x != nil {
		return x.P2Str
	}
	return ""
}

func (x *PRRecieve_PRRP2Scheme) GetP2Bugle() string {
	if x != nil {
		return x.P2Bugle
	}
	return ""
}

type PRRecieve_PRRP5Scheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P5Bytes []byte `protobuf:"bytes,1,opt,name=p5bytes,proto3" json:"p5bytes,omitempty"`
	P5Int   int32  `protobuf:"varint,2,opt,name=p5int,proto3" json:"p5int,omitempty"`
}

func (x *PRRecieve_PRRP5Scheme) Reset() {
	*x = PRRecieve_PRRP5Scheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PRRecieve_PRRP5Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRRecieve_PRRP5Scheme) ProtoMessage() {}

func (x *PRRecieve_PRRP5Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRRecieve_PRRP5Scheme.ProtoReflect.Descriptor instead.
func (*PRRecieve_PRRP5Scheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{2, 2}
}

func (x *PRRecieve_PRRP5Scheme) GetP5Bytes() []byte {
	if x != nil {
		return x.P5Bytes
	}
	return nil
}

func (x *PRRecieve_PRRP5Scheme) GetP5Int() int32 {
	if x != nil {
		return x.P5Int
	}
	return 0
}

type UserScan_UserScanData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bugle13 *UserScan_UserScanData_BugleScheme   `protobuf:"bytes,1,opt,name=Bugle13,proto3" json:"Bugle13,omitempty"`
	Tachyon *UserScan_UserScanData_TachyonScheme `protobuf:"bytes,2,opt,name=Tachyon,proto3" json:"Tachyon,omitempty"`
	Bugle15 *UserScan_UserScanData_BugleScheme   `protobuf:"bytes,3,opt,name=Bugle15,proto3" json:"Bugle15,omitempty"`
}

func (x *UserScan_UserScanData) Reset() {
	*x = UserScan_UserScanData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserScan_UserScanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScan_UserScanData) ProtoMessage() {}

func (x *UserScan_UserScanData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScan_UserScanData.ProtoReflect.Descriptor instead.
func (*UserScan_UserScanData) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UserScan_UserScanData) GetBugle13() *UserScan_UserScanData_BugleScheme {
	if x != nil {
		return x.Bugle13
	}
	return nil
}

func (x *UserScan_UserScanData) GetTachyon() *UserScan_UserScanData_TachyonScheme {
	if x != nil {
		return x.Tachyon
	}
	return nil
}

func (x *UserScan_UserScanData) GetBugle15() *UserScan_UserScanData_BugleScheme {
	if x != nil {
		return x.Bugle15
	}
	return nil
}

type UserScan_UserScanData_BugleScheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BugleId  int32  `protobuf:"varint,1,opt,name=BugleId,proto3" json:"BugleId,omitempty"`
	BugleNum string `protobuf:"bytes,2,opt,name=BugleNum,proto3" json:"BugleNum,omitempty"`
	Bugle    string `protobuf:"bytes,3,opt,name=Bugle,proto3" json:"Bugle,omitempty"`
}

func (x *UserScan_UserScanData_BugleScheme) Reset() {
	*x = UserScan_UserScanData_BugleScheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserScan_UserScanData_BugleScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScan_UserScanData_BugleScheme) ProtoMessage() {}

func (x *UserScan_UserScanData_BugleScheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScan_UserScanData_BugleScheme.ProtoReflect.Descriptor instead.
func (*UserScan_UserScanData_BugleScheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *UserScan_UserScanData_BugleScheme) GetBugleId() int32 {
	if x != nil {
		return x.BugleId
	}
	return 0
}

func (x *UserScan_UserScanData_BugleScheme) GetBugleNum() string {
	if x != nil {
		return x.BugleNum
	}
	return ""
}

func (x *UserScan_UserScanData_BugleScheme) GetBugle() string {
	if x != nil {
		return x.Bugle
	}
	return ""
}

type UserScan_UserScanData_TachyonScheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tachyon   []byte `protobuf:"bytes,1,opt,name=Tachyon,proto3" json:"Tachyon,omitempty"`
	Timestamp int32  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserScan_UserScanData_TachyonScheme) Reset() {
	*x = UserScan_UserScanData_TachyonScheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserScan_UserScanData_TachyonScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserScan_UserScanData_TachyonScheme) ProtoMessage() {}

func (x *UserScan_UserScanData_TachyonScheme) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserScan_UserScanData_TachyonScheme.ProtoReflect.Descriptor instead.
func (*UserScan_UserScanData_TachyonScheme) Descriptor() ([]byte, []int) {
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *UserScan_UserScanData_TachyonScheme) GetTachyon() []byte {
	if x != nil {
		return x.Tachyon
	}
	return nil
}

func (x *UserScan_UserScanData_TachyonScheme) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_github_com_danhol86_dhmessagesapi_messages_protos_proto protoreflect.FileDescriptor

var file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDesc = []byte{
	0x0a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e,
	0x68, 0x6f, 0x6c, 0x38, 0x36, 0x2f, 0x64, 0x68, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x0b, 0x53, 0x45, 0x4e, 0x44, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x64, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x70, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x32,
	0x22, 0x87, 0x05, 0x0a, 0x08, 0x50, 0x52, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a,
	0x02, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x52, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x52,
	0x43, 0x50, 0x31, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x31, 0x12, 0x2e, 0x0a,
	0x02, 0x70, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x52, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x52,
	0x43, 0x50, 0x32, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x32, 0x12, 0x2e, 0x0a,
	0x02, 0x70, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x52, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x52,
	0x43, 0x50, 0x33, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x33, 0x1a, 0xea, 0x01,
	0x0a, 0x0b, 0x50, 0x52, 0x43, 0x50, 0x31, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x75, 0x67, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50,
	0x52, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x52, 0x43, 0x50, 0x31, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x65, 0x2e, 0x50, 0x52, 0x43, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x02, 0x70, 0x31, 0x1a, 0x75, 0x0a, 0x0b, 0x50, 0x52, 0x43, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x6f,
	0x75, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x1a, 0x65, 0x0a, 0x0b, 0x50, 0x52,
	0x43, 0x50, 0x32, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x72, 0x6f,
	0x77, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x72, 0x6f, 0x77,
	0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x62, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x96, 0x01, 0x0a, 0x0b, 0x50, 0x52, 0x43, 0x50, 0x33, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x43, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x52, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x50, 0x52, 0x43, 0x50, 0x33, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x2e, 0x50, 0x52,
	0x43, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x31, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x65, 0x52, 0x02, 0x70, 0x31, 0x1a, 0x42, 0x0a, 0x14, 0x50, 0x52, 0x43, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x31, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6e,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x65, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x65, 0x6e, 0x63, 0x22, 0xa1, 0x03, 0x0a, 0x09, 0x50,
	0x52, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x12, 0x2f, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x52, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x2e, 0x50, 0x52, 0x52, 0x50, 0x31, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x31, 0x12, 0x2f, 0x0a, 0x02, 0x70, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x50, 0x52, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x2e, 0x50, 0x52, 0x52, 0x50, 0x32,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65,
	0x79, 0x65, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x65,
	0x6e, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x31, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x31, 0x12, 0x2f, 0x0a, 0x02, 0x70, 0x35,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x52, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x2e, 0x50, 0x52, 0x52, 0x50,
	0x35, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x02, 0x70, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x1a,
	0x2b, 0x0a, 0x0b, 0x50, 0x52, 0x52, 0x50, 0x31, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x51, 0x0a, 0x0b,
	0x50, 0x52, 0x52, 0x50, 0x32, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x32, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x32, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x32, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x32, 0x73, 0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x32, 0x62, 0x75, 0x67, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x32, 0x62, 0x75, 0x67, 0x6c, 0x65, 0x1a,
	0x3d, 0x0a, 0x0b, 0x50, 0x52, 0x52, 0x50, 0x35, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x35, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x35, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x35, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x35, 0x69, 0x6e, 0x74, 0x22, 0x34,
	0x0a, 0x02, 0x51, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x70, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x70, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x70, 0x33, 0x22, 0xcb, 0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x61,
	0x6e, 0x12, 0x33, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x63, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x89, 0x03, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x63, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x45, 0x0a, 0x07, 0x42, 0x75, 0x67, 0x6c, 0x65,
	0x31, 0x33, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x07, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x31, 0x33, 0x12, 0x47,
	0x0a, 0x07, 0x54, 0x61, 0x63, 0x68, 0x79, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x63, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x54, 0x61, 0x63, 0x68, 0x79, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x07,
	0x54, 0x61, 0x63, 0x68, 0x79, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x07, 0x42, 0x75, 0x67, 0x6c, 0x65,
	0x31, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x07, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x31, 0x35, 0x1a, 0x59,
	0x0a, 0x0b, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x42, 0x75, 0x67, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x67, 0x6c, 0x65,
	0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x75, 0x67, 0x6c, 0x65,
	0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x42, 0x75, 0x67, 0x6c, 0x65, 0x1a, 0x47, 0x0a, 0x0d, 0x54, 0x61, 0x63,
	0x68, 0x79, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61,
	0x63, 0x68, 0x79, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x54, 0x61, 0x63,
	0x68, 0x79, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x61, 0x6e, 0x68, 0x6f, 0x6c, 0x38, 0x36, 0x2f, 0x64, 0x68, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescOnce sync.Once
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescData = file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDesc
)

func file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescGZIP() []byte {
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescOnce.Do(func() {
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescData)
	})
	return file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDescData
}

var file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_github_com_danhol86_dhmessagesapi_messages_protos_proto_goTypes = []interface{}{
	(*SENDMESSAGE)(nil),                               // 0: messages.SENDMESSAGE
	(*PRCreate)(nil),                                  // 1: messages.PRCreate
	(*PRRecieve)(nil),                                 // 2: messages.PRRecieve
	(*QR)(nil),                                        // 3: messages.QR
	(*UserScan)(nil),                                  // 4: messages.UserScan
	(*PRCreate_PRCP1Scheme)(nil),                      // 5: messages.PRCreate.PRCP1Scheme
	(*PRCreate_PRCP2Scheme)(nil),                      // 6: messages.PRCreate.PRCP2Scheme
	(*PRCreate_PRCP3Scheme)(nil),                      // 7: messages.PRCreate.PRCP3Scheme
	(*PRCreate_PRCP1Scheme_PRCDateTime)(nil),          // 8: messages.PRCreate.PRCP1Scheme.PRCDateTime
	(*PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme)(nil), // 9: messages.PRCreate.PRCP3Scheme.PRCEncryptedP1Scheme
	(*PRRecieve_PRRP1Scheme)(nil),                     // 10: messages.PRRecieve.PRRP1Scheme
	(*PRRecieve_PRRP2Scheme)(nil),                     // 11: messages.PRRecieve.PRRP2Scheme
	(*PRRecieve_PRRP5Scheme)(nil),                     // 12: messages.PRRecieve.PRRP5Scheme
	(*UserScan_UserScanData)(nil),                     // 13: messages.UserScan.UserScanData
	(*UserScan_UserScanData_BugleScheme)(nil),         // 14: messages.UserScan.UserScanData.BugleScheme
	(*UserScan_UserScanData_TachyonScheme)(nil),       // 15: messages.UserScan.UserScanData.TachyonScheme
}
var file_github_com_danhol86_dhmessagesapi_messages_protos_proto_depIdxs = []int32{
	5,  // 0: messages.PRCreate.p1:type_name -> messages.PRCreate.PRCP1Scheme
	6,  // 1: messages.PRCreate.p2:type_name -> messages.PRCreate.PRCP2Scheme
	7,  // 2: messages.PRCreate.p3:type_name -> messages.PRCreate.PRCP3Scheme
	10, // 3: messages.PRRecieve.p1:type_name -> messages.PRRecieve.PRRP1Scheme
	11, // 4: messages.PRRecieve.p2:type_name -> messages.PRRecieve.PRRP2Scheme
	12, // 5: messages.PRRecieve.p5:type_name -> messages.PRRecieve.PRRP5Scheme
	13, // 6: messages.UserScan.Data:type_name -> messages.UserScan.UserScanData
	8,  // 7: messages.PRCreate.PRCP1Scheme.p1:type_name -> messages.PRCreate.PRCP1Scheme.PRCDateTime
	9,  // 8: messages.PRCreate.PRCP3Scheme.p1:type_name -> messages.PRCreate.PRCP3Scheme.PRCEncryptedP1Scheme
	14, // 9: messages.UserScan.UserScanData.Bugle13:type_name -> messages.UserScan.UserScanData.BugleScheme
	15, // 10: messages.UserScan.UserScanData.Tachyon:type_name -> messages.UserScan.UserScanData.TachyonScheme
	14, // 11: messages.UserScan.UserScanData.Bugle15:type_name -> messages.UserScan.UserScanData.BugleScheme
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_github_com_danhol86_dhmessagesapi_messages_protos_proto_init() }
func file_github_com_danhol86_dhmessagesapi_messages_protos_proto_init() {
	if File_github_com_danhol86_dhmessagesapi_messages_protos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SENDMESSAGE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRRecieve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserScan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate_PRCP1Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate_PRCP2Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate_PRCP3Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate_PRCP1Scheme_PRCDateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRCreate_PRCP3Scheme_PRCEncryptedP1Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRRecieve_PRRP1Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRRecieve_PRRP2Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PRRecieve_PRRP5Scheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserScan_UserScanData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserScan_UserScanData_BugleScheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserScan_UserScanData_TachyonScheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_danhol86_dhmessagesapi_messages_protos_proto_goTypes,
		DependencyIndexes: file_github_com_danhol86_dhmessagesapi_messages_protos_proto_depIdxs,
		MessageInfos:      file_github_com_danhol86_dhmessagesapi_messages_protos_proto_msgTypes,
	}.Build()
	File_github_com_danhol86_dhmessagesapi_messages_protos_proto = out.File
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_rawDesc = nil
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_goTypes = nil
	file_github_com_danhol86_dhmessagesapi_messages_protos_proto_depIdxs = nil
}
