// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: mygoapp/dhmessagesapi/messages/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId   string         `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	MessageName string         `protobuf:"bytes,2,opt,name=MessageName,proto3" json:"MessageName,omitempty"`
	MessageData *Item_MData    `protobuf:"bytes,4,opt,name=MessageData,proto3" json:"MessageData,omitempty"`
	ConvId      string         `protobuf:"bytes,7,opt,name=ConvId,proto3" json:"ConvId,omitempty"`
	RecipientId string         `protobuf:"bytes,9,opt,name=RecipientId,proto3" json:"RecipientId,omitempty"`
	Content     *Item_MContent `protobuf:"bytes,10,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Item) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *Item) GetMessageData() *Item_MData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *Item) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *Item) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *Item) GetContent() *Item_MContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *MyMessage) Reset() {
	*x = MyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessage) ProtoMessage() {}

func (x *MyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessage.ProtoReflect.Descriptor instead.
func (*MyMessage) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MyMessage) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*MyMessage      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Updates []*MyMessage      `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	Update  *ConnectionUpdate `protobuf:"bytes,6,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMessage) GetItems() []*MyMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateMessage) GetUpdates() []*MyMessage {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateMessage) GetUpdate() *ConnectionUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type ConnectionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateCode int32 `protobuf:"varint,2,opt,name=UpdateCode,proto3" json:"UpdateCode,omitempty"`
}

func (x *ConnectionUpdate) Reset() {
	*x = ConnectionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionUpdate) ProtoMessage() {}

func (x *ConnectionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionUpdate.ProtoReflect.Descriptor instead.
func (*ConnectionUpdate) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionUpdate) GetUpdateCode() int32 {
	if x != nil {
		return x.UpdateCode
	}
	return 0
}

type Messageupdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*MessageItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Messageupdate) Reset() {
	*x = Messageupdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Messageupdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messageupdate) ProtoMessage() {}

func (x *Messageupdate) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messageupdate.ProtoReflect.Descriptor instead.
func (*Messageupdate) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Messageupdate) GetItems() []*MessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MessageItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId     string               `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	MessageStatus *MessageItem_MStatus `protobuf:"bytes,2,opt,name=MessageStatus,proto3" json:"MessageStatus,omitempty"`
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessageItem) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageItem) GetMessageStatus() *MessageItem_MStatus {
	if x != nil {
		return x.MessageStatus
	}
	return nil
}

type Item_MData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageCode  int32  `protobuf:"varint,2,opt,name=MessageCode,proto3" json:"MessageCode,omitempty"`
	MesssageName string `protobuf:"bytes,4,opt,name=MesssageName,proto3" json:"MesssageName,omitempty"`
}

func (x *Item_MData) Reset() {
	*x = Item_MData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item_MData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item_MData) ProtoMessage() {}

func (x *Item_MData) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item_MData.ProtoReflect.Descriptor instead.
func (*Item_MData) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Item_MData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Item_MData) GetMessageCode() int32 {
	if x != nil {
		return x.MessageCode
	}
	return 0
}

func (x *Item_MData) GetMesssageName() string {
	if x != nil {
		return x.MesssageName
	}
	return ""
}

type Item_MContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId    string              `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	MessageValue *Item_MContentValue `protobuf:"bytes,2,opt,name=MessageValue,proto3" json:"MessageValue,omitempty"`
}

func (x *Item_MContent) Reset() {
	*x = Item_MContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item_MContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item_MContent) ProtoMessage() {}

func (x *Item_MContent) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item_MContent.ProtoReflect.Descriptor instead.
func (*Item_MContent) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Item_MContent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Item_MContent) GetMessageValue() *Item_MContentValue {
	if x != nil {
		return x.MessageValue
	}
	return nil
}

type Item_MContentValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageText string `protobuf:"bytes,1,opt,name=MessageText,proto3" json:"MessageText,omitempty"`
}

func (x *Item_MContentValue) Reset() {
	*x = Item_MContentValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item_MContentValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item_MContentValue) ProtoMessage() {}

func (x *Item_MContentValue) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item_MContentValue.ProtoReflect.Descriptor instead.
func (*Item_MContentValue) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Item_MContentValue) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

type MessageItem_MStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusId   string `protobuf:"bytes,2,opt,name=StatusId,proto3" json:"StatusId,omitempty"`
	StatusText string `protobuf:"bytes,5,opt,name=StatusText,proto3" json:"StatusText,omitempty"`
}

func (x *MessageItem_MStatus) Reset() {
	*x = MessageItem_MStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageItem_MStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem_MStatus) ProtoMessage() {}

func (x *MessageItem_MStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem_MStatus.ProtoReflect.Descriptor instead.
func (*MessageItem_MStatus) Descriptor() ([]byte, []int) {
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP(), []int{5, 0}
}

func (x *MessageItem_MStatus) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *MessageItem_MStatus) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

var File_mygoapp_dhmessagesapi_messages_messages_proto protoreflect.FileDescriptor

var file_mygoapp_dhmessagesapi_messages_messages_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x79, 0x67, 0x6f, 0x61, 0x70, 0x70, 0x2f, 0x64, 0x68, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xf3, 0x03, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x76, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x76,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x4d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x67, 0x0a, 0x05, 0x4d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x4d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x6a, 0x0a, 0x08, 0x4d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x0c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x2e, 0x4d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x31, 0x0a, 0x0d,
	0x4d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22,
	0x31, 0x0a, 0x09, 0x4d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x2d, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x32,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x32, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x43, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x2e, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x45, 0x0a, 0x07, 0x4d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x65, 0x78, 0x74, 0x42, 0x18,
	0x5a, 0x16, 0x64, 0x68, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescOnce sync.Once
	file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescData = file_mygoapp_dhmessagesapi_messages_messages_proto_rawDesc
)

func file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescGZIP() []byte {
	file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescOnce.Do(func() {
		file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescData)
	})
	return file_mygoapp_dhmessagesapi_messages_messages_proto_rawDescData
}

var file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mygoapp_dhmessagesapi_messages_messages_proto_goTypes = []interface{}{
	(*Item)(nil),                // 0: messages.Item
	(*MyMessage)(nil),           // 1: messages.MyMessage
	(*UpdateMessage)(nil),       // 2: messages.UpdateMessage
	(*ConnectionUpdate)(nil),    // 3: messages.ConnectionUpdate
	(*Messageupdate)(nil),       // 4: messages.Messageupdate
	(*MessageItem)(nil),         // 5: messages.MessageItem
	(*Item_MData)(nil),          // 6: messages.Item.MData
	(*Item_MContent)(nil),       // 7: messages.Item.MContent
	(*Item_MContentValue)(nil),  // 8: messages.Item.MContentValue
	(*MessageItem_MStatus)(nil), // 9: messages.MessageItem.MStatus
}
var file_mygoapp_dhmessagesapi_messages_messages_proto_depIdxs = []int32{
	6, // 0: messages.Item.MessageData:type_name -> messages.Item.MData
	7, // 1: messages.Item.Content:type_name -> messages.Item.MContent
	0, // 2: messages.MyMessage.items:type_name -> messages.Item
	1, // 3: messages.UpdateMessage.items:type_name -> messages.MyMessage
	1, // 4: messages.UpdateMessage.updates:type_name -> messages.MyMessage
	3, // 5: messages.UpdateMessage.update:type_name -> messages.ConnectionUpdate
	5, // 6: messages.Messageupdate.items:type_name -> messages.MessageItem
	9, // 7: messages.MessageItem.MessageStatus:type_name -> messages.MessageItem.MStatus
	8, // 8: messages.Item.MContent.MessageValue:type_name -> messages.Item.MContentValue
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_mygoapp_dhmessagesapi_messages_messages_proto_init() }
func file_mygoapp_dhmessagesapi_messages_messages_proto_init() {
	if File_mygoapp_dhmessagesapi_messages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Messageupdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item_MData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item_MContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item_MContentValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageItem_MStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mygoapp_dhmessagesapi_messages_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mygoapp_dhmessagesapi_messages_messages_proto_goTypes,
		DependencyIndexes: file_mygoapp_dhmessagesapi_messages_messages_proto_depIdxs,
		MessageInfos:      file_mygoapp_dhmessagesapi_messages_messages_proto_msgTypes,
	}.Build()
	File_mygoapp_dhmessagesapi_messages_messages_proto = out.File
	file_mygoapp_dhmessagesapi_messages_messages_proto_rawDesc = nil
	file_mygoapp_dhmessagesapi_messages_messages_proto_goTypes = nil
	file_mygoapp_dhmessagesapi_messages_messages_proto_depIdxs = nil
}
